#include "pdb.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* All nine HTM edges cost one, including half turns and inverse turns. */
static int build_pdb(unsigned pattern, uint8_t packed[PDB_BYTES])
{
    uint8_t *distance = malloc(PDB_STATES);
    uint32_t *queue = malloc((size_t) PDB_STATES * sizeof *queue);
    if (!distance || !queue) {
        free(distance);
        free(queue);
        return 0;
    }
    for (uint32_t rank = 0; rank < PDB_STATES; ++rank) {
        pdb_state_t state = pdb_unrank(rank);
        if (pdb_rank(&state) != rank) {
            fputs("partial rank/unrank check failed\n", stderr);
            free(distance);
            free(queue);
            return 0;
        }
    }
    memset(distance, UINT8_MAX, PDB_STATES);
    pdb_state_t goal = pdb_goal(pattern);
    uint32_t goal_rank = pdb_rank(&goal);
    uint32_t head = 0, tail = 1;
    unsigned diameter = 0;
    queue[0] = goal_rank;
    distance[goal_rank] = 0;
    while (head < tail) {
        uint32_t here = queue[head++];
        pdb_state_t state = pdb_unrank(here);
        for (unsigned face = 0; face < 3; ++face) {
            pdb_state_t next = state;
            for (unsigned turn = 0; turn < 3; ++turn) {
                next = pdb_quarter_turn(next, face);
                uint32_t there = pdb_rank(&next);
                if (distance[there] != UINT8_MAX)
                    continue;
                unsigned d = distance[here] + 1U;
                /* 15 is reserved for missing entries. Never silently truncate. */
                if (d >= 15 || tail >= PDB_STATES) {
                    fputs("PDB cannot be packed into four bits\n", stderr);
                    free(distance);
                    free(queue);
                    return 0;
                }
                distance[there] = (uint8_t) d;
                queue[tail++] = there;
                if (d > diameter)
                    diameter = d;
            }
        }
    }
    if (tail != PDB_STATES) {
        fputs("abstract BFS did not reach all states\n", stderr);
        free(distance);
        free(queue);
        return 0;
    }
    for (uint32_t i = 0; i < PDB_BYTES; ++i)
        packed[i] = (uint8_t) (distance[2U * i] | (distance[2U * i + 1U] << 4U));
    printf("PDB %c: %u abstract states; goal rank %u; diameter %u; %u bytes\n",
           'A' + pattern, (unsigned) tail, (unsigned) goal_rank, diameter,
           (unsigned) PDB_BYTES);
    free(distance);
    free(queue);
    return 1;
}

static int write_binary(const char *filename, const uint8_t packed[PDB_BYTES])
{
    FILE *file = fopen(filename, "wb");
    if (!file) {
        perror(filename);
        return 0;
    }
    int ok = fwrite(packed, 1, PDB_BYTES, file) == PDB_BYTES;
    if (fclose(file) != 0)
        ok = 0;
    if (!ok)
        fprintf(stderr, "could not write %s\n", filename);
    return ok;
}

static int write_header(const uint8_t packed[PDB_COUNT][PDB_BYTES])
{
    const char *temporary = "pdb_data.h.tmp";
    FILE *file = fopen(temporary, "w");
    if (!file) {
        perror(temporary);
        return 0;
    }
    fputs("/* Generated by generate_pdb.c. Do not edit. */\n"
          "#ifndef MINIRUBIK_PDB_DATA_H\n#define MINIRUBIK_PDB_DATA_H\n"
          "#include <stdint.h>\n"
          "static const uint8_t pdb_tables[2][34020] = {\n", file);
    for (unsigned pattern = 0; pattern < PDB_COUNT; ++pattern) {
        fputs("    {\n", file);
        for (uint32_t i = 0; i < PDB_BYTES; ++i) {
            if (i % 16U == 0)
                fputs("        ", file);
            fprintf(file, "0x%02x,", packed[pattern][i]);
            fputc(i % 16U == 15U || i + 1U == PDB_BYTES ? '\n' : ' ', file);
        }
        fputs("    },\n", file);
    }
    /* A search coordinate packs permutation in bits 0..9, orientation in
     * bits 10..16. For each permutation/face store the new permutation and
     * the twist delta. Both patterns use the same abstract transition rules.
     */
    fputs("};\nstatic const uint32_t coordinate_turn[3][840] = {\n", file);
    for (unsigned face = 0; face < 3; ++face) {
        fputs("    {\n", file);
        for (unsigned p = 0; p < PDB_PERMUTATIONS; ++p) {
            pdb_state_t state = pdb_unrank(p * PDB_ORIENTATIONS);
            state = pdb_quarter_turn(state, face);
            uint32_t rank = pdb_rank(&state);
            uint32_t entry = rank / PDB_ORIENTATIONS |
                             ((rank % PDB_ORIENTATIONS) << 10U);
            if (p % 8U == 0)
                fputs("        ", file);
            fprintf(file, "%u,", (unsigned) entry);
            fputc(p % 8U == 7U ? '\n' : ' ', file);
        }
        fputs("    },\n", file);
    }
    fputs("};\nstatic const uint8_t orientation_add[81][81] = {\n", file);
    for (unsigned delta = 0; delta < PDB_ORIENTATIONS; ++delta) {
        pdb_state_t d = pdb_unrank(delta);
        fputs("    {\n        ", file);
        for (unsigned o = 0; o < PDB_ORIENTATIONS; ++o) {
            pdb_state_t state = pdb_unrank(o);
            for (unsigned i = 0; i < PDB_CORNERS; ++i)
                state.ori[i] = (uint8_t) ((state.ori[i] + d.ori[i]) % 3U);
            fprintf(file, "%u,", (unsigned) pdb_rank(&state));
            if (o + 1U == PDB_ORIENTATIONS)
                fputc('\n', file);
            else if (o % 16U == 15U)
                fputs("\n        ", file);
            else
                fputc(' ', file);
        }
        fputs("    },\n", file);
    }
    fputs("};\n#endif\n", file);
    int ok = !ferror(file);
    if (fclose(file) != 0)
        ok = 0;
    if (ok && rename(temporary, "pdb_data.h") != 0)
        ok = 0;
    if (!ok)
        perror("could not write pdb_data.h");
    return ok;
}

int main(int argc, char **argv)
{
    if (argc != 1) {
        fprintf(stderr, "usage: %s (writes PDB files in the current directory)\n",
                argv[0]);
        return 2;
    }
    uint8_t (*packed)[PDB_BYTES] = malloc(PDB_COUNT * PDB_BYTES);
    if (!packed) {
        fputs("could not allocate packed PDBs\n", stderr);
        return 1;
    }
    for (unsigned pattern = 0; pattern < PDB_COUNT; ++pattern) {
        if (!build_pdb(pattern, packed[pattern])) {
            free(packed);
            return 1;
        }
    }
    int ok = write_binary("pdb_a.bin", packed[0]) &&
             write_binary("pdb_b.bin", packed[1]) &&
             write_header((const uint8_t (*)[PDB_BYTES]) packed);
    free(packed);
    if (!ok)
        return 1;
    puts("Wrote pdb_a.bin, pdb_b.bin and pdb_data.h; PDB bytes: 68040; transition bytes: 16641");
    return fflush(stdout) != 0 || ferror(stdout);
}
